flowchart TD
    1[aaaaa]
    1 --> 2[bbbbb]
    2 --> A1[ccccc] 
    2 --> A2[ddddd]
    2 --> A3[eeeee]
    2 --> A4[fffff]
    A2 --> A[hhhhh]
    A1 & A2 --> 5[iiiii]
    5 & A4 --> A5[jjjjj]
    5 --> 6[kkkkk]
    6 --> 7[lllll]
    8 --> 9[mmmmm]
    X[nnnnn] --> 11
    7 --> 10[ooooo] & 11[ppppp] & 12[qqqqq] & 14[rrrrr]
    XX[sssss]
    12 & XX --> B[ttttt]
    11 & 12 & 9 --> 13[uuuuu]
    11 & XX --> 15[vvvvv]
    10 & 15 --> 16[wwwww]
    13 --> 17[xxxxx]
    17 --> 18[yyyyy] & 19[zzzzz] & 20[11111] & 21[22222]
    15 & 18 & 21 --> C1[33333]
    C1 --> C2[44444]
    C2 & 16 --> C2_1[55555]
    XXX[66666] & C2 --> C3[77777]
    C3 --> C4[88888]
    C4 --> C2_1
    C4 ---> C5[99999] & C6[a1a1a1a1a1]
    A4 & 16 & C3 --> XXXX[a2a2a2a2a2]
    B & XX & XXXX & 16 & C4 --> I1[a3a3a3a3a3]
    I1 --> I2[a4a4a4a4a4] & I3[a5a5a5a5a5]
    I2 --> I2_2[a6a6a6a6a6]
    I2 --> I2_1[a7a7a7a7a7]
    I2_2 --> I3 & I5
    I3 --> I4[a8a8a8a8a8] --> I5[a9a9a9a9a9]
    I3 --> I6[b1b1b1b1b1] --> I7[b2b2b2b2b2]
    17 & C1 & C5 & C6 --> C7[b3b3b3b3b3]
    15 --> ZZ[b4b4b4b4b4] & I2 --> I8
    I2 & I6 --> I8[b5b5b5b5b5]
    I2 --> I9[b6b6b6b6b6]
    I7 --> E[b7b7b7b7b7]
    17 & C5 & C7 --> C8[b8b8b8b8b8]
    C7 --> C9[b9b9b9b9b9]
    C8 & 19 --> R1[c1c1c1c1c1]
