flowchart TD
    1[Levantine-Mesopotamian-Religions]
    1 --> 2[Abramism]
    2 --> A1[Polytheistic Judah Religion] 
    2 --> A2[Polytheistic Israel Religion]
    2 --> A3[Polytheistic Phoenician Religion]
    2 --> A4[Polytheistic Arab Religion]
    A2 --> A[Ten Lost Tribes Religions]
    A1 & A2 --> 5[Monolatrist Yahwism]
    5 & A4 --> A5[Edomite-Nabatean Religion]
    5 --> 6[Babylonian Monotheist Yahwism]
    6 --> 7[Judean Yahwism] & 8[Samaritan Yahwism]
    8 --> 9[Samaritan religion]
    X[Mesopotamian Paganism] --> 11
    7 --> 10[Saducee Judaism] & 11[Pharisaic Judaism] & 12[Essene Judaism] & 14[Fourth Philosophy]
    XX[Zoroastrian Gnostic Religion]
    12 & XX --> B[Mandean religion]
    11 & 12 & 9 --> 13[Yeshuaite Judaism]
    11 & XX --> 15[Rabbanite Judaism]
    10 & 15 --> 16[Karaite Judaism]
    13 --> 17[Jewish Christianity]
    17 --> 18[Johnian Jewish-Christianity] & 19[Ebionite Jewish-Christianity] & 20[Alexite Jewish-Christianity] & 21[Nazarene Jewish-Christianity]
    15 & 18 & 21 --> C1[Pauline Christianity]
    C1 --> C2[Apostolic Ignatian Christianity]
    C2 & 16 --> C2_1[Coptic-Ethiopian Christianity]
    XXX[Greco-Roman Paganism] & C2 --> C3[Greek Chrysostomian and Latin Isidorean Christianity]
    C3 --> C4[Iconic Christianity]
    C4 --> C2_1
    C4 ---> C5[Orthodox Christianity] & C6[Catholic Christianity]
    A4 & 16 & C3 --> XXXX[Hanifite Religions]
    B & XX & XXXX & 16 & C4 --> I1[Muhammadan Islam]
    I1 --> I2[Sunni Islam] & I3[Old Shia Islam]
    I2 --> I2_2[Mu'tazili Islam]
    I2 --> I2_1[Athari Islam]
    I2_2 --> I3 & I5
    I3 --> I4[Huwarej Islam Sects] --> I5[Ibadi Islam]
    I3 --> I6[New Shia Islam] --> I7[Shia Originated Religions]
    17 & C1 & C5 & C6 --> C7[Protestant Christianity]
    15 --> ZZ[Sabbateans] & I2 --> I8
    I2 & I6 --> I8[Sufi Islam]
    I2 --> I9[Ahmadi Islam]
    I7 --> E[Bahai Religion]
    17 & C5 & C7 --> C8[Unitarian Christianity]
    C7 --> C9[Evangalical Christianity]
    C8 & 19 --> R1[Neo-Ebionite Jewish Christianity]
