flowchart TD
    1[Levantine-Mesopotamian-Religions]
    1 --> 2[Abramism]
    2 --> A1[Polytheistic Judah Religion] 
    2 --> A2[Polytheistic Israel Religion]
    2 --> A3[Polytheistic Phoenician Religion]
    2 --> A4[Polytheistic Arab Religion]
    A2 --> A[Ten Lost Tribes Religions]
    A1 & A2 --> 5[Monolatrist Yahwism]
    5 & A4 --> A5[Edomite-Nabatean Religion]
    5 --> 6[Babylonian Monotheist Yahwism]
    6 --> 7[Judean Yahwism] & 8[Samaritan Yahwism]
    8 --> 9[Samaritan religion]
    X[Mesopotamian Paganism] --> 11
    7 --> 10[Saducee Judaism] & 11[Pharisaic Judaism] & 12[Essene Judaism] & 14[Fourth Philosophy]
    XX[Zoroastrian Gnostic Religion]
    12 & XX --> B[Mandean religion]
    11 & 12 & 9 --> 13[Yeshuaite Judaism]
    11 & XX --> 15[Rabbanite Judaism]
    10 & 15 --> 16[Karaite Judaism]
